name: flipper_charts
description: flipper charts scaffold.
version: 0.0.1
author:
homepage:
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flipper:
    path: '../..'
dev_dependencies:
  flutter_test:
    sdk: flutter
  