arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: flipper_localizations.dart
# output-class: FlipperLocalizations
# preferred-supported-locales:
#   - en
# use-deferred-loading: false
