final List<Map<String, dynamic>> mockUnits = [
  {'name': 'Per Item', 'value': '', 'active': true},
  {'name': 'Per Kilogram (kg)', 'value': 'kg', 'active': false},
  {'name': 'Per Cup (c)', 'value': 'c', 'active': false},
  {'name': 'Per Liter (l)', 'value': 'l', 'active': false},
  {'name': 'Per Pound (lb)', 'value': 'lb', 'active': false},
  {'name': 'Per Pint (pt)', 'value': 'pt', 'active': false},
  {'name': 'Per Acre (ac)', 'value': 'ac', 'active': false},
  {'name': 'Per Centimeter (cm)', 'value': 'cm', 'active': false},
  {'name': 'Per Cubic Footer (cu ft)', 'value': 'cu ft', 'active': false},
  {'name': 'Per Day (day)', 'value': 'day', 'active': false},
  {'name': 'Footer (ft)', 'value': 'ft', 'active': false},
  {'name': 'Per Gram (g)', 'value': 'g', 'active': false},
  {'name': 'Per Hour (hr)', 'value': 'hr', 'active': false},
  {'name': 'Per Minute (min)', 'value': 'min', 'active': false},
  {'name': 'Per Acre (ac)', 'value': 'ac', 'active': false},
  {'name': 'Per Cubic Inch (cu in)', 'value': 'cu in', 'active': false},
  {'name': 'Per Cubic Yard (cu yd)', 'value': 'cu yd', 'active': false},
  {'name': 'Per Fluid Ounce (fl oz)', 'value': 'fl oz', 'active': false},
  {'name': 'Per Gallon (gal)', 'value': 'gal', 'active': false},
  {'name': 'Per Inch (in)', 'value': 'in', 'active': false},
  {'name': 'Per Kilometer (km)', 'value': 'km', 'active': false},
  {'name': 'Per Meter (m)', 'value': 'm', 'active': false},
  {'name': 'Per Mile (mi)', 'value': 'mi', 'active': false},
  {'name': 'Per Milligram (mg)', 'value': 'mg', 'active': false},
  {'name': 'Per Milliliter (mL)', 'value': 'mL', 'active': false},
  {'name': 'Per Millimeter (mm)', 'value': 'mm', 'active': false},
  {'name': 'Per Millisecond (ms)', 'value': 'ms', 'active': false},
  {'name': 'Per Ounce (oz)', 'value': 'oz', 'active': false},
  {'name': 'Per  Quart (qt)', 'value': 'qt', 'active': false},
  {'name': 'Per Second (sec)', 'value': 'sec', 'active': false},
  {'name': 'Per Shot (sh)', 'value': 'sh', 'active': false},
  {'name': 'Per Square Centimeter (sq cm)', 'value': 'sq cm', 'active': false},
  {'name': 'Per Square Foot (sq ft)', 'value': 'sq ft', 'active': false},
  {'name': 'Per Square Inch (sq in)', 'value': 'sq in', 'active': false},
  {'name': 'Per Square Kilometer (sq km)', 'value': 'sq km', 'active': false},
  {'name': 'Per Square Meter (sq m)', 'value': 'sq m', 'active': false},
  {'name': 'Per Square Mile (sq mi)', 'value': 'sq mi', 'active': false},
  {'name': 'Per Square Yard (sq yd)', 'value': 'sq yd', 'active': false},
  {'name': 'Per Stone (st)', 'value': 'st', 'active': false},
  {'name': 'Per Yard (yd)', 'value': 'yd', 'active': false}
];
