name: chat
description: flipper models scaffold.
version: 0.0.1
author:
homepage:
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flipper:
    path: '../..'
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  auto_route_generator:
  injectable_generator: 
  stacked_generator:
  

flutter:

  uses-material-design: true

  assets:
    - assets/images/
